init:
  - git config --global core.autocrlf false

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12
    - nodejs_version: 13

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version && npm --version
  - npm test

build: off

matrix:
  fast_finish: true
